name: Build & Deploy StrynexUi to Azure Static Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_STATIC_WEBAPP_NAME: strynexUi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # default token
          action: "upload"
          app_location: "/" # root of your repo
          output_location: "build" # location of the built app
